name: Build Full Changelog
 
on:
  workflow_dispatch:
 
jobs:
  changelog:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout project branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: project
 
      - name: Create project branch if not exists
        run: git checkout -B project
 
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh jq
 
      - name: Generate changelog from all releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "# Changelog" > NEW_CHANGELOG.md
            echo "" >> NEW_CHANGELOG.md
            gh api -H "Accept: application/vnd.github+json" repos/${GITHUB_REPOSITORY}/releases --paginate > releases.json
            jq -r --arg repo "${GITHUB_REPOSITORY}" "
              sort_by(.published_at) | reverse[] | \"## [
