name: Sync GitHub Releases to CHANGELOG
 
on:
  release:
    types: [published]
 
jobs:
  update-changelog:
    if: github.event.release.prerelease == false  # ✅ Skip prereleases
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Get and format release notes
        id: generate
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
const changelogPath = 'CHANGELOG.md';
 
            const release = context.payload.release;
            const tagName = release.tag_name;
const releaseName = release.name || tagName;
            const body = (release.body || '').trim();
            const date = new Date(release.published_at).toISOString().split('T')[0];
            const repo = context.repo;
 
            // Convert #123 to issue/PR links
            const linkedBody = body.replace(/#(\d+)/g, (_, n) => {
return `[#${n}](https://github.com/${repo.owner}/${repo.repo}/issues/${n})`;
            });
 
            const newEntry = `## [${releaseName}] - ${date}\n\n${linkedBody}\n\n`;
 
            let oldChangelog = '';
            if (fs.existsSync(changelogPath)) {
              oldChangelog = fs.readFileSync(changelogPath, 'utf8');
            }
 
            fs.writeFileSync(changelogPath, newEntry + oldChangelog);
 
      - name: Commit and push changelog
        run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add CHANGELOG.md
git commit -m "chore: update CHANGELOG.md for release ${{ github.event.release.tag_name }}"
          git push
