name: Release to Changelog



on:

  release:

    types: [published]



jobs:

  update-changelog:

    runs-on: ubuntu-latest



    steps:

    - name: Checkout code

      uses: actions/checkout@v3



    - name: Extract release info

      id: extract

      run: |

        echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

        echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV

        echo "${{ github.event.release.body }}" >> $GITHUB_ENV

        echo "EOF" >> $GITHUB_ENV



- name: Update CHANGELOG.md

      run: |

echo "## [${RELEASE_TAG}] - $(date +'%Y-%m-%d')" > temp.md

echo "${RELEASE_BODY}" >> temp.md

echo -e "\n\n" >> temp.md

cat CHANGELOG.md >> temp.md

mv temp.md CHANGELOG.md



    - name: Commit and push changelog

      run: |

git config --global user.name "github-actions[bot]"

git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

git add CHANGELOG.md

        git commit -m "chore: update changelog for $RELEASE_TAG"

        git push
